@startuml
actor User
boundary LayananActivity
control LayananAdapter
entity DataLayanan

User -> LayananActivity: Membuka aplikasi
LayananActivity -> LayananAdapter: Menampilkan list dari DataLayanan
LayananAdapter -> LayananActivity: Kembali ke list dari DataLayanan
LayananActivity -> User: Menampilkan list dari layanan
User -> LayananActivity: klik pada layanan
LayananActivity -> LayananAdapter: Menerima pilihan dari layanan
LayananAdapter -> LayananActivity: kembali pada pilihan layanan
LayananActivity -> User: Menampilkan detail dari pilihan layanan
User -> LayananActivity: Klik item_url
LayananActivity -> User: Membuka Url pada halaman web
@enduml
```